In [6]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [7]:
df = pd.read_excel("Delinquency_prediction_dataset.xlsx")

In [8]:
df.head()

,Customer_ID,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,CUST0001,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,EMP,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,CUST0002,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,CUST0003,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,CUST0004,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,CUST0005,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           500 non-null    object
 1   Age                   500 non-null    int64
 2   Income                461 non-null    float64
 3   Credit_Score          498 non-null    float64
 4   Credit_Utilization    500 non-null    float64
 5   Missed_Payments       500 non-null    int64
 6   Delinquent_Account    500 non-null    int64
 7   Loan_Balance          471 non-null    float64
 8   Debt_to_Income_Ratio  500 non-null    float64
 9   Employment_Status     500 non-null    object
 10  Account_Tenure        500 non-null    int64
 11  Credit_Card_Type      500 non-null    object
 12  Location              500 non-null    object
 13  Month_1               500 non-null    object
 14  Month_2               500 non-null    object
 15  Month_3               500 non-null    object
 16  Month_4               500 non-null    object
 17  Month_5               500 non-null    object
 18  Month_6               500 non-null    object
dtypes: float64(5), int64(4), object(10)
memory usage: 74.3+ KB

In [10]:
df.isnull().sum()

Customer_ID              0
Age                      0
Income                  39
Credit_Score             2
Credit_Utilization       0
Missed_Payments          0
Delinquent_Account       0
Loan_Balance            29
Debt_to_Income_Ratio     0
Employment_Status        0
Account_Tenure           0
Credit_Card_Type         0
Location                 0
Month_1                  0
Month_2                  0
Month_3                  0
Month_4                  0
Month_5                  0
Month_6                  0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['Income'] = df['Income'].fillna(df['Income'].median())
df['Credit_Score'] = df['Credit_Score'].fillna(df['Credit_Score'].median())
df['Loan_Balance'] = df['Loan_Balance'].fillna(df['Loan_Balance'].median())

In [13]:
df.isnull().sum()

Customer_ID             0
Age                     0
Income                  0
Credit_Score            0
Credit_Utilization      0
Missed_Payments         0
Delinquent_Account      0
Loan_Balance            0
Debt_to_Income_Ratio    0
Employment_Status       0
Account_Tenure          0
Credit_Card_Type        0
Location                0
Month_1                 0
Month_2                 0
Month_3                 0
Month_4                 0
Month_5                 0
Month_6                 0
dtype: int64

In [14]:
df.to_excel("cleaned_delinquency_dataset.xlsx", index=False)

In [15]:
df.shape

(500, 19)

In [16]:
df.columns

Index(['Customer_ID', 'Age', 'Income', 'Credit_Score', 'Credit_Utilization',
       'Missed_Payments', 'Delinquent_Account', 'Loan_Balance',
       'Debt_to_Income_Ratio', 'Employment_Status', 'Account_Tenure',
       'Credit_Card_Type', 'Location', 'Month_1', 'Month_2', 'Month_3',
       'Month_4', 'Month_5', 'Month_6'],
      dtype='object')

In [17]:
df.describe()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Account_Tenure
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,46.266000,108323.586000,577.750000,0.491446,2.968000,0.160000,48487.480000,0.298862,9.740000
std,16.187629,51523.389667,168.543244,0.197103,1.946935,0.366973,28536.522206,0.094521,5.923054
min,18.000000,15404.000000,301.000000,0.050000,0.000000,0.000000,612.000000,0.100000,0.000000
25%,33.000000,67610.500000,418.750000,0.356486,1.000000,0.000000,24847.000000,0.233639,5.000000
50%,46.500000,107658.000000,586.000000,0.485636,3.000000,0.000000,45776.000000,0.301634,10.000000
75%,59.250000,152572.250000,725.750000,0.634440,5.000000,0.000000,73809.500000,0.362737,15.000000
max,74.000000,199943.000000,847.000000,1.025843,6.000000,1.000000,99620.000000,0.552956,19.000000

In [18]:
df.columns

Index(['Customer_ID', 'Age', 'Income', 'Credit_Score', 'Credit_Utilization',
       'Missed_Payments', 'Delinquent_Account', 'Loan_Balance',
       'Debt_to_Income_Ratio', 'Employment_Status', 'Account_Tenure',
       'Credit_Card_Type', 'Location', 'Month_1', 'Month_2', 'Month_3',
       'Month_4', 'Month_5', 'Month_6'],
      dtype='object')

In [19]:
df['Delinquent_Account'].value_counts()

Delinquent_Account
0    420
1     80
Name: count, dtype: int64

In [20]:
df['Delinquent_Account'].value_counts(normalize=True) * 100

Delinquent_Account
0    84.0
1    16.0
Name: proportion, dtype: float64

In [21]:
payment_cols = ['Month_1','Month_2','Month_3','Month_4','Month_5','Month_6']

for col in payment_cols:
    print("\n", col)
    print(df[col].value_counts())

 Month_1
Month_1
On-time    177
Missed     164
Late       159
Name: count, dtype: int64

 Month_2
Month_2
Late       173
Missed     167
On-time    160
Name: count, dtype: int64

 Month_3
Month_3
Late       169
On-time    169
Missed     162
Name: count, dtype: int64

 Month_4
Month_4
Late       181
Missed     160
On-time    159
Name: count, dtype: int64

 Month_5
Month_5
Missed     187
On-time    162
Late       151
Name: count, dtype: int64

 Month_6
Month_6
Late       172
Missed     168
On-time    160
Name: count, dtype: int64

In [22]:
pd.crosstab(df['Employment_Status'],
            df['Delinquent_Account'])

Delinquent_Account   0   1
Employment_Status
EMP                 69  12
Employed            67  15
Self-employed       67  13
Unemployed          75  18
employed            65  12
retired             77  10

In [23]:
df['Employment_Status'] = df['Employment_Status'].replace({
    'EMP': 'Employed',
    'employed': 'Employed'
})

In [24]:
pd.crosstab(df['Employment_Status'],
            df['Delinquent_Account'])

Delinquent_Account    0   1
Employment_Status
Employed            201  39
Self-employed        67  13
Unemployed           75  18
retired              77  10

In [25]:
df.groupby('Delinquent_Account')[['Income',
                                  'Credit_Score',
                                  'Loan_Balance']].mean()

                           Income  Credit_Score  Loan_Balance
Delinquent_Account
0                   107335.361905    575.197619  48555.135714
1                   113511.762500    591.150000  48132.287500

In [26]:
df.select_dtypes(include='object').columns

Index(['Customer_ID', 'Employment_Status', 'Credit_Card_Type', 'Location',
       'Month_1', 'Month_2', 'Month_3', 'Month_4', 'Month_5', 'Month_6'],
      dtype='object')

In [27]:
df = df.drop('Customer_ID', axis=1)

In [30]:
from sklearn.preprocessing import StandardScaler

le = StandardScaler()

df['Employment_Status'] = le.fit_transform(df['Employment_Status'])

ValueError: could not convert string to float: 'Employed'

In [ ]:
payment_cols = ['Month_1','Month_2','Month_3',
                'Month_4','Month_5','Month_6']

for col in payment_cols:
    df[col] = le.fit_transform(df[col])

In [31]:
df.head()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Employment_Status,Account_Tenure,Credit_Card_Type,Location,Month_1,Month_2,Month_3,Month_4,Month_5,Month_6
0,56,165580.0,398.0,0.390502,3,0,16310.0,0.317396,Employed,18,Student,Los Angeles,Late,Late,Missed,Late,Missed,Late
1,69,100999.0,493.0,0.312444,6,1,17401.0,0.196093,Self-employed,0,Standard,Phoenix,Missed,Missed,Late,Missed,On-time,On-time
2,46,188416.0,500.0,0.359930,0,0,13761.0,0.301655,Self-employed,1,Platinum,Chicago,Missed,Late,Late,On-time,Missed,Late
3,32,101672.0,413.0,0.371400,3,0,88778.0,0.264794,Unemployed,15,Platinum,Phoenix,Late,Missed,Late,Missed,Late,Late
4,60,38524.0,487.0,0.234716,2,0,13316.0,0.510583,Self-employed,11,Standard,Phoenix,Missed,On-time,Missed,Late,Late,Late

In [32]:
df.select_dtypes(include='object').columns

Index(['Employment_Status', 'Credit_Card_Type', 'Location', 'Month_1',
       'Month_2', 'Month_3', 'Month_4', 'Month_5', 'Month_6'],
      dtype='object')

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

In [38]:
X = df.drop('Delinquent_Account', axis=1)
y = df['Delinquent_Account']

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [40]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 17)
(100, 17)
(400,)
(100,)

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)
rf_model.fit(X_train_scaled, y_train)

y_pred = rf_model.predict(X_test_scaled)

In [43]:
y_pred = rf_model.predict(X_test_scaled)
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.84

In [45]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[84  0]
 [16  0]]
              precision    recall  f1-score   support

           0       0.84      1.00      0.91        84
           1       0.00      0.00      0.00        16

    accuracy                           0.84       100
   macro avg       0.42      0.50      0.46       100
weighted avg       0.71      0.84      0.77       100

In [46]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=5000)

lr_model.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [47]:
y_pred_lr = lr_model.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr, zero_division=0))

Accuracy: 0.84
[[84  0]
 [16  0]]
              precision    recall  f1-score   support

           0       0.84      1.00      0.91        84
           1       0.00      0.00      0.00        16

    accuracy                           0.84       100
   macro avg       0.42      0.50      0.46       100
weighted avg       0.71      0.84      0.77       100

In [49]:
lr_balanced = LogisticRegression(
    max_iter=5000,
    class_weight='balanced'
)

lr_balanced.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=5000)

In [50]:
y_pred_bal = lr_balanced.predict(X_test)

In [51]:
print("Accuracy:", accuracy_score(y_test, y_pred_bal))
print(confusion_matrix(y_test, y_pred_bal))
print(classification_report(y_test, y_pred_bal, zero_division=0))

Accuracy: 0.51
[[44 40]
 [ 9  7]]
              precision    recall  f1-score   support

           0       0.83      0.52      0.64        84
           1       0.15      0.44      0.22        16

    accuracy                           0.51       100
   macro avg       0.49      0.48      0.43       100
weighted avg       0.72      0.51      0.58       100